name: Vocab-Builder CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sushantkumar007/vocab-builder-backend
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sushantkumar007/vocab-builder-backend
      IMAGE_TAG: ${{ github.sha }}
    needs:
      - build-and-push
    steps:
      - name: SSH into the server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SWARM_MANAGER_HOST }}
          username: ${{ secrets.SWARM_MANAGER_USERNAME }}
          key: ${{ secrets.SWARM_MANAGER_SSH_KEY }}
          port: ${{ secrets.SWARM_MANAGER_SSH_PORT }}
          script: |
            set -e
            cd ~/vocab-builder-backend

            # pull compose file from the git
            git fetch origin
            git restore --source=origin/main compose.yaml

            # pull the latest image from Docker Hub
            docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

            export IMAGE_TAG=${{ env.IMAGE_TAG }}
            # deploy the stack with the updated image
            docker stack deploy -c compose.yaml vocab-builder-stack
